# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maws < Formula
  desc "MFA AWS CLI"
  homepage "https://github.com/favadi/maws"
  version "0.0.5"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/favadi/maws/releases/download/v0.0.5/maws_0.0.5_Darwin_arm64.tar.gz"
      sha256 "c49914a76c759a69c8b0cb094e2fc959edaa1572a5c51f5ef891b15ee0af72bf"

      def install
        bin.install "maws"
        bin.install "docker-credential-mecr-login"
        (bash_completion/"maws_bash_completer").write <<~EOS
          complete -C aws_completer maws
        EOS
        (zsh_completion/"_maws").write <<~EOS
          #compdef maws
          _maws () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
            if [[ -f $e ]]; then source $e; fi
            complete -C aws_completer maws
          }
        EOS
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/maws/releases/download/v0.0.5/maws_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "8bb3d10633266b14338c6f7100a7d35b8e62f08dca7fbc81d84af8fbc31c0305"

      def install
        bin.install "maws"
        bin.install "docker-credential-mecr-login"
        (bash_completion/"maws_bash_completer").write <<~EOS
          complete -C aws_completer maws
        EOS
        (zsh_completion/"_maws").write <<~EOS
          #compdef maws
          _maws () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
            if [[ -f $e ]]; then source $e; fi
            complete -C aws_completer maws
          }
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/favadi/maws/releases/download/v0.0.5/maws_0.0.5_Linux_arm64.tar.gz"
      sha256 "5c91cbd2a345e68694f28c555946e33087e3e759c550178ec85e24eb4d85f6d7"

      def install
        bin.install "maws"
        bin.install "docker-credential-mecr-login"
        (bash_completion/"maws_bash_completer").write <<~EOS
          complete -C aws_completer maws
        EOS
        (zsh_completion/"_maws").write <<~EOS
          #compdef maws
          _maws () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
            if [[ -f $e ]]; then source $e; fi
            complete -C aws_completer maws
          }
        EOS
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/maws/releases/download/v0.0.5/maws_0.0.5_Linux_x86_64.tar.gz"
      sha256 "3099a090a45dbdae61a2cc706639ee270db9b620b39767c5a135ddfce6a48570"

      def install
        bin.install "maws"
        bin.install "docker-credential-mecr-login"
        (bash_completion/"maws_bash_completer").write <<~EOS
          complete -C aws_completer maws
        EOS
        (zsh_completion/"_maws").write <<~EOS
          #compdef maws
          _maws () {
            local e
            e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
            if [[ -f $e ]]; then source $e; fi
            complete -C aws_completer maws
          }
        EOS
      end
    end
  end

  depends_on "awscli"
end
