# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maws < Formula
  desc "MFA AWS CLI"
  homepage "https://github.com/favadi/maws"
  version "0.0.2"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/favadi/maws/releases/download/v0.0.2/maws_0.0.2_Darwin_arm64.tar.gz"
      sha256 "c29fac677ad88fcfc53588b2b26865682cbea935bd071cd3f623cd70e8471dc2"

      def install
        bin.install "maws"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/maws/releases/download/v0.0.2/maws_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "3430d8489081eaf3bf70ea91b81aac76cd644c7615294f5c3ebe9c0183f93157"

      def install
        bin.install "maws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/favadi/maws/releases/download/v0.0.2/maws_0.0.2_Linux_arm64.tar.gz"
      sha256 "54a845e9205654cdf323db03554e0c665cf232b8c44f407817ccc725b0c8033a"

      def install
        bin.install "maws"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/maws/releases/download/v0.0.2/maws_0.0.2_Linux_x86_64.tar.gz"
      sha256 "2e84d4082604b4e1ac6862bb99583a5fb6cfc6d67bddfcc5ef5a4ad3ec130024"

      def install
        bin.install "maws"
      end
    end
  end

  depends_on "awscli"

  def post_install
    (bash_completion/"maws_bash_completer").write <<~EOS
      complete -C aws_completer maws
    EOS
    (zsh_completion/"_maws").write <<~EOS
      #compdef maws
      _maws () {
        local e
        e=$(dirname ${funcsourcetrace[1]%:*})/aws_zsh_completer.sh
        if [[ -f $e ]]; then source $e; fi
      }
    EOS
  end
end
